[patch.crates-io]
wgpu_glyph = { git = "https://github.com/hecrj/wgpu_glyph", branch = "master" }

[profile.release]
lto = true

[workspace]
resolver = "2"
members = ["cli", "gui", "crawler", "diff"]
