[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu", branch = "master" }
wgpu_glyph = { git = "https://github.com/hecrj/wgpu_glyph", branch = "master" }

[profile.release]
lto = true

[workspace]
resolver = "2"
members = ["gui", "crawler", "diff"]
default-members = ["gui"]
